:doctitle: Using variables
:tabcolumns: d,h,d,h,d,d,d,d,d,d,d,d,d,d,d,d
include::../commonhead.adoc[]

[#_part1_1]
:source-language: java
:numbered!:

== MOOC Material Week 2

:numbered:
== Using and updating variables

We usually want to change the value of an existing variable. This can be done using the normal
    assignment statement. In the next example, we increase the value of the variable `age` by
    one:

[source,java]
----

int age = 1;

System.out.println(age);  // prints 1
age = age + 1;            // the new value of age is the old value of age + 1
System.out.println(age);  // prints 2
----

The `age = age + 1` statement increments the value of the variable `age` by one.
    It is also possible to increment a variable by one as bellow:

[source,java]
----

int age = 1;

System.out.println(age);  // prints 1
age++;                    // means the same as age = age + 1
System.out.println(age);  // prints 2
----

Another example:

[source,java]
----

int length = 100;

System.out.println(length);  // prints 100
length = length - 50;
System.out.println(length);  // prints 50
length = length * 2;
System.out.println(length);  // prints 100
length = length / 4;
System.out.println(length);  // prints 25
length--;                    // means the same as length = length - 1;
System.out.println(length);  // prints 24
----

include::{exercises}/ex25.adoc[]

include::{exercises}/ex26.adoc[]


== More loops

We have previously learned to use repetition using the `while (true)` loop, which repeats
commands until the `break` command is used.

The `break` command is not the only way to end a loop. A common structure for a loop
    is `while (condition)`, where the condition can be any statement with a truth
    value. This means that the condition works exactly like conditions in an `if` statements.

In the following example, we print the numbers 1, 2, …, 10. When the value of the variable
    `number` increases above 10, the condition of the `while` statement is no longer
    true and the loop ends.

[source,java]
----

int number = 1;

while (number &lt; 11) {
    System.out.println(number);
    number++;  // number++ means the same as number = number + 1
}
----

The example above can be read "as long as the variable number is less than 11, print the variable and
    increment it by one".

Above, the variable `number` was incremented in each iteration of the loop. Generally the change can be
    anything, meaning that the variable used in the condition does not always need to be incremented. For
    example:

[source,java]
----

int number = 1024;

while (number &gt;= 1) {
    System.out.println(number);
    number = number / 2;
}
----


[TIP]
====
* You can find all the NetBeans tips http://mooc.fi/courses/general/programming/#netbeans-tips[here] +
* *Auto-completion of your code* +
  If you have, for example, the variable `String familyName;` in your code, you do
  not need to always write `familyName`. Try what happens when you type in
  `f` and then press CTRL and space simultaneously. You can also use auto-completion
  with commands like `while` by typing in `w` and then CTRL + space.

* *sout* +
    Remember that you can get the text `System.out.println("")` by typing
    `sout` and pressing the `tab` key (located to the left of the q key)

====


include::{exercises}/ex27.adoc[]

include::{exercises}/ex28.adoc[]

include::{exercises}/ex29.adoc[]

include::{exercises}/ex30.adoc[]

include::{exercises}/ex31.adoc[]


=== Assignment operations

Because changing the value of a variable is a very common operation, Java has special assignment
operations for it.

[source,java]
----
int length = 100;

length += 10;  // same as length = length + 10;
length -= 50;  // same as length = length - 50;
----

When performing the assignment operation on an existing variable, it is written as
`variable operation= change`, for example `variable += 5`. Note that a variable must
be defined before you can assign a value to it. Defining a variable is done by specifying the variable
type and the name of the variable.

The following example will not work because the type of the variable `length` has not been
defined.

[source,java]
----
length = length + 100;  // error!
length += 100;          // error!
----

When the type is defined, the operations will also work.

[source,java]
----
int length = 0;
length = length + 100;
length += 100;

// the variable length now holds the value 200
----

There are also other assignment operations:

[source,java]
----

int length = 100;

length *= 10;   // same as length = length * 10;
length /= 100;  // same as length = length / 100;
length %= 3;    // same as length = length % 3;

// the variable length now holds the value 1
----

Often during a loop, the value of a variable is calculated based on repetition. The following program
calculates 3*4 somewhat clumsily as the sum 3+3+3+3:

[source,java]
----

int result = 0;

int i = 0;
while (i &lt; 4) {
   result = result + 3;
   i++;  // means the same as i = i + 1;
}
----

In the beginning `result = 0`. During the loop, the value of the variable is incremented
by 3 on each iteration. Because there are 4 iterations, the value of the variable is 3*4 in the end.

Using the assignment operator introduced above, we can achieve the same behavior as follows:

[source,java]
----

int result = 0;

int i = 0;
while (i &lt; 4) {
   result += 3;  // this is the same as result = result + 3;
   i++;          // means the same as i = i+1;
}
----

include::{exercises}/ex32.adoc[]

include::{exercises}/ex33.adoc[]

include::{exercises}/ex34.adoc[]

include::{exercises}/ex35.adoc[]


=== Infinite loops

One of the classic errors in programming is to accidentally create an infinite loop. In the next example
we try to print "Never again shall I program an eternal loop!" 10 times:

[source,java]
----
int i = 0;

while (i < 10) {
    System.out.println("Never again shall I program an eternal loop!");
}
----

The variable `i`, which determines is supposed to index the loops, is initially set to 0. The block is
looped as long as the condition `i < 10` is true. But something funny happens. Because the value of the variable `i` is never changed, the condition stays true forever.

=== Ending a while loop

So far, we have used the while loop with a structure similar to this:

[source,java]
----
int i = 1;
while (i &lt; 10) {
    // Some code.
    i++;
}
----

With the structure above, the variable `i` remembers the number of times the the loop has
been executed. The condition to end the loop is based on comparing the value of `i`.

Let us now recall how a while loop is stopped. Ending a while loop does not always need to be based on
the amount of loops. The next example program asks for the user's age. If the given age is not in the range
5-85, the program prints a message and asks for the user's age again. As you can see, the condition for the
while loop can be any expression that results in a boolean (truth value).

[source,java]
----
System.out.println("Type your age: ");

int age = Integer.parseInt(reader.nextLine());

while (age < 5 || age > 85) {  // age less than 5 OR greater than 85
    System.out.println("You are lying!");
    if (age < 5) {
        System.out.println("You are so young that you cannot know how to write!");
    } else if (age > 85) {
        System.out.println("You are so old that you cannot know how to use a computer!");
    }

    System.out.println("Type your age again: ");
    age = Integer.parseInt(reader.nextLine());
}

System.out.println("Your age is " + age);
----

The program could also have been implemented using the good old `while (true)` structure:

[source,java]
----
System.out.println("Type your age ");
int age;
while (true) {
    age = Integer.parseInt(reader.nextLine());

    if (age >= 5 && age <= 85) {  // age between 5 AND 85
        break;  // end the loop
    }

    System.out.println("You are lying!");
    if (age < 5) {
        System.out.println("You are so young that you cannot know how to write!");
    } else {  // that means age is over 85
        System.out.println("You are so old that you cannot know how to use a computer!");
    }

    System.out.println("Type your age again: ");
}

System.out.println("Your age is " + age);
----

include::{exercises}/ex36.adoc[]

[TIP]
====
*Creating a program in small steps* +

In these exercises we actually created one single program, but programming happened in very small
steps. This is *ALWAYS* the preferred way to program.

When you are programming something, no matter if it is an exercise or a project of your own, it is
advised to do it in very tiny pieces. Do not ever try to solve the whole problem in one go. Start with
something easy, something you know that you can do. In this recent set of exercises, for example, we
focused first on stopping the program when the user types -1. When one part of the program is complete and
working, we can move on to work out the solution for the next sub-problem of the big main
problem.

Some of the exercises in this course are sliced into smaller pieces like the set of exercises we
just introduced. Usually the pieces need to be sliced again into smaller pieces depending on the
problem. It is advised that you execute the whole program after almost every new line of
code you write. This enables you to be sure that your solution is going in the right and working
direction.
====

== Methods

We have so far used many different commands of Java: assignment, calculations, comparison, if
structures and while structures. We have been using a "command" `System.out.println()`
to print text. We can also count the maximum of two numbers with the help of the "command"
`Math.max()`. We are also familiar with `reader.nextLine()`, usually seen together
with `Integer.parseInt()`.

If we take a closer look, we notice that those commands differ from if and while (etc). The first
difference is that after the command there are brackets () and sometimes an input for the command inside
those brackets. Actually, the commands ending with brackets are not called commands, but
*methods*.

Technically speaking, a method is a piece of code that can be called from different places of the program code.
The line of code `System.out.println("I am a parameter given to the method!")` means
that we call a method that actually handles the printing. After the method has been executed we go back
to where we called the method, and continue executing. The input given to the method inside the brackets is
called a <i>method parameter</i>.

In addition to a parameter, the method can also have a return value, for example, a familiar line of
code:

[source,java]
----
int number = Integer.parseInt( reader.nextLine() );
----

includes two method calls. First the inner method `reader.nextLine` is called. That method
has the integer typed by the user as a return value. Next the outer method `Integer.parseInt` is
called. As a parameter for that method there is the string of characters that was received from the
`reader.nextLine` method as a return value. The return value for the method
`Integer.parseInt` is the string of characters transformed into an integer (whole number).

Method names also seem to include a dot, for example `reader.nextLine()`. Actually the method
name starts after the dot, here it is `nextLine()`. The first part of the command that comes
before the dot shows whose method is in question. Here the method belongs to the reader, which means that we have the
<em>reader's</em> method <em>nextLine</em>. Later we will learn more precisely about the owner of the method
(or the name on the left side of the dot). An attentive reader will notice that the method
`System.out.println()` has two dots. Here, the method name is println and
`System.out` is the owner of the method. Roughly `System.out` means the computer
monitor.

This far we have been using ready-made methods from Java libraries. Next we will learn how to create our own
methods.

=== Self-written methods

This far we have been using a programming style where code is written (and read and executed) from top
to bottom.

It was mentioned before that "a method is a piece of code that can be called from different places
of the program code". Ready-made methods of Java have been used since our very first program.

In addition to using these ready-made methods  programmers can write their own methods for programs
to call. In the real world, it is really exceptional if the program does not include any self-written
methods. From now on almost every program we create during this course will include self-written
methods.

The methods are written in the program body outside the main's braces ( { and } ) but still inside
the outermost braces, for example like this: :

[source,java]
----
import java.util.Scanner;

public class ProgramBody {
    public static void main(String[] args) {
        Scanner reader = new Scanner(System.in);
        // program code
    }

    // self-written methods
}
----

Let us create a method `greet`.

[source,java]
----
public static void greet() {
    System.out.println("Greetings from the world of methods!");
}
----

And let us place it in the right spot.

[source,java]
----
import java.util.Scanner;

public class ProgramBody {
    public static void main(String[] args) {
        Scanner reader = new Scanner(System.in);
        // program code
    }

    // self-written methods
    public static void greet() {
        System.out.println("Greetings from the world of methods!");
    }
}
----

In order to define a new method we need to write two things. In the first row of the method definition,
you will find the name of the method, in this case <i>greet</i>. On the left side of the name you will find the definitions
`public static void`. On the next line, the code block marked by the braces ({ and }).
Inside it, the method's code, or the commands that will be executed when the method is
called. Our method `greet` only writes one line of text to the screen.

It is easy to call a self-written method. It happens by writing the method name, brackets () and a
semicolon. In the next example main (or the main program) calls for our method, first once and then several
times.

[source,java]
----
import java.util.Scanner;

public class ProgramBody {
    public static void main(String[] args) {
        Scanner reader = new Scanner(System.in);

        // program code
        System.out.println("Let us try if we can get to the method world:");
        greet();

        System.out.println("It seems like we can, let us try again:");
        greet();
        greet();
        greet();
    }

    // self-written methods
    public static void greet() {
        System.out.println("Greetings from the world of methods!");
    }
}
----

When the program is executed, we see the following output:

[source]
----
Let us try if we can get to the method world:
Greetings from the world of methods!
It seems like we can, let us try again:
Greetings from the world of methods!
Greetings from the world of methods!
Greetings from the world of methods!
----

What is noteworthy here is the execution order of the program code. The execution starts with the main
program's (or main's) lines of code, from top to bottom, one by one. When the line of code to be executed
happens to be a method call, the lines of code in the method block are executed again one by one. When
the method block ends, the execution continues from the place where the method was called. To be exact, the
execution continues from the next line after the original method call.

To be even more exact, the main program is also a method. When the program starts, the operation system
calls for the main method. That means that the main method is the starting point of the program and the execution
starts from the first code line of main. The program execution ends when it reaches the end of
main.

From now on when we introduce methods, we will not point out that they need to be written in the right
place inside the program code. For example, a method cannot be defined inside another method.

include::{exercises}/ex37.adoc[]

include::{exercises}/ex38.adoc[]

=== Method parameters

We can make our methods more useful by giving it _parameters_! Parameters are variables
that we define inside brackets in the first line, just after the method name. When the
method is called, the parameters are assigned values.

In the next example we define a method with a parameter, its name will be `greet` and its
parameter will be a variable of the type String called `name`.


[source,java]
----
public static void greet(String name) {
    System.out.println("Hi " + name + ", greetings from the world of methods!");
}
----

Let us next call the `greet` method so that on the first try we give its parameter the value
`Matt` and on the second try `Arthur`.

[source,java]
----
public static void main(String[] args) {
    greet("Matt");
    greet("Arthur");
}
----

[source]
----
Hi Matt, greetings from the world of methods!
Hi Arthur, greetings from the world of methods!
----

More complicated expressions can also be used as a parameter for our self-written methods, the same way
we used them together with the ready-made `System.out.println()` method.

[source,java]
----
public static void main(String[] args) {
    String name1 = "Anne";
    String name2 = "Green";
    greet( name1 + " " + name2 );

    int age = 24;
    greet("John " + age + " years");
}
----

[source]
----
Hi Anne Green, greetings from the world of methods!
Hi John 24 years, greetings from the world of methods!
----

In both cases the method has only one parameter. The value for the parameter is calculated before
calling the method. In the first case the parameter value comes from the String concatenation (a cool word
that means putting the text together) `name1 + " " + name2`. The value for the
concatenation is <i>Anne Green</i>. In the second case we get the parameter value from the String
concatenation `"John " + age + " years"`.

=== Multiple parameters

A method can be defined to have more than one parameter. In this case, the parameters are always listed in the
same order.

[source,java]
----
public static void greet(String name, String greetingsFrom) {
    System.out.println("Hi " + name + ", greetings from " + greetingsFrom);
}
----

[source,java]
----
String who = "Matt";
String greetings = "Alabama";

greet(who, greetings);
greet(who, greetings + " from Nevada");
----

In the last `greet` function (or method) call the second parameter is formed by concatenating (or
adding) the text “from Nevada” to the variable `greetings`. This is done before the actual function
call.

[source]
----
Hi Matt, greetings from Alabama
Hi Matt, greetings from Alabama from Nevada
----

=== Method calling another method

Methods can also be called outside of main. Methods can call each other! Let us create a
method `greetManyTimes` that greets the user many times getting assistance from the method
`greet`:

[source,java]
----
public static void greet(String name) {
    System.out.println("Hi " + name + ", greetings from the world of methods!");
}

public static void greetManyTimes(String name, int times) {
    int i = 0;
    while ( i &lt; times ) {
        greet(name);
        i++;
    }

}

public static void main(String[] args) {
    greetManyTimes("Anthony", 3);
    System.out.println("and");
    greetManyTimes("Martin", 2);
}
----

Output:

[source]
----
Hi Anthony, greetings from the world of methods!
Hi Anthony, greetings from the world of methods!
Hi Anthony, greetings from the world of methods!
and
Hi Martin, greetings from the world of methods!
Hi Martin, greetings from the world of methods!
----

include::{exercises}/ex39.adoc[]

include::{exercises}/ex40.adoc[]

include::{exercises}/ex41.adoc[]

include::{exercises}/ex42.adoc[]

'''
