++++
<div class='exgroup'><h4>Exercise 39: Printing</h4>
++++

++++
<div class='ex'><details class='ex'><summary>Exercise 39.1: Printing stars</summary>
++++

Create a method `printStars` that prints the given amount of stars and a line break.

Create the method in the following body:

[source,java]
----

private static void printStars(int amount) {
    // you can print one star with the command
    // System.out.print("*");
    // call this command amount times
}

public static void main(String[] args) {
    printStars(5);
    printStars(3);
    printStars(9);
}
----

The program output:

[source]
----
*****
***
*********
----
++++
</details></div><!-- end ex 39.1-->
++++

*Note:* You can upload exercises that contain many parts to the exercise robot even though
you have not finished all parts. In that case, the robot complains about tests in the unfinished parts of the exercise, but gives you points for all tests that pass.

++++
<div class='ex'><details class='ex'><summary>Exercise 39.2: Printing a square</summary>
++++
<h4></h4>

Create a method `printSquare(int sideSize)` that prints a square using our previous
method printStars. The method call `printSquare(4)`, for example, prints the following:

[source]
----
****
****
****
****
----

*Note:* in order to complete the exercise it is not enough that the outprint looks good. Inside
the printSquare method the printing must be done using the printStars method.

++++
</details></div><!-- end ex 39.2-->
++++

When you are in the middle of making your program, you should verify the correctness of your methods
by writing some test code into your main method.

++++
<div class='ex'><details class='ex'><summary>Exercise 39.3: Printing a rectangle</summary>
++++

Create a method `printRectangle(int width, int height)` that prints a rectangle using the
printStars method. The call `printRectangle(17,3)`, for example, has the following
output:

[source]
----
*****************
*****************
*****************
----
++++
</details></div><!-- end ex 39.3-->
++++

++++
<div class='ex'><details class='ex'><summary>Exercise 39.4: Printing a left-aligned triangle</summary>
++++

Create the method `printTriangle(int size)` that prints a triangle using the printStars
method. The method call `printTriangle(4)`, for example, has the following output:

[source]
----
*
**
***
****
----
++++
</details></div><!-- end ex 39.4-->
++++

++++
</div> <!--exgroup 39 -->
++++
