++++
<div class='exgroup'><h4>Exercise 40: Printing Like A Boss</h4>
++++

++++
<div class='ex'><details class='ex'><summary>Exercise 40.1: Printing stars and whitespaces</summary>
++++

Create a method `printWhitespaces(int size)` that prints the given amount of whitespaces.
Them method should not print a line break.

Reimplement or copy the method `printStars(int size)` from the
previous exercise.
++++
</details></div><!-- end ex 40.1-->
++++

++++
<div class='ex'><details class='ex'><summary>Exercise 40.2: Printing a right-aligned triangle</summary>
++++

Create the method `printTriangle(int size)` that prints a triangle using the methods `printWhitespaces` and `printStars`. *Note:* do not
print anything in the method itself, just call the helper methods to do the actual printing.

For example, the method call `printTriangle(4)` has the following output:

[source]
----
   *
  **
 ***
****
----
++++
</details></div><!-- end ex 40.2-->
++++

++++
<div class='ex'><details class='ex'><summary>Exercise 40.3: Printing a Christmas tree</summary>
++++

Create the method `xmasTree(int height)` that prints a Christmas tree using the mehtods
`printWhitespaces` and `printStars`. A Christmas tree consists of a triangle of
given height and a stand. The stand is two stars tall and three stars wide and it is located in the
center of the bottom of the triangle.

*Note:* do not print anything in the method itself, just call the
helper methods to do the actual printing.

The method call `xmasTree(4)`, for example, has the following output:

[source]
----
   *
  ***
 *****
*******
  ***
  ***
----

The method call `xmasTree(10)` has the following output:

[source]
----
         *
        ***
       *****
      *******
     *********
    ***********
   *************
  ***************
 *****************
*******************
        ***
        ***
----

*Second note:* You don't need to worry about heights below 3!
++++
</details></div><!-- end ex 40.3-->
++++
++++
</div> <!--ex group 40-->
++++
