++++
<div class='ex'><details class='ex'><summary>Exercise 87: Apartment comparison </summary>
++++


The information system of a Housing service represents the apartments it has for sale using
  objects of the following class:
[source,java]
----
public class Apartment {
    private int rooms;
    private int squareMeters;
    private int pricePerSquareMeter;

    public Apartment(int rooms, int squareMeters, int pricePerSquareMeter){
        this.rooms = rooms;
        this.squareMeters = squareMeters;
        this.pricePerSquareMeter = pricePerSquareMeter;
    }
}
----
Next you should implement a couple of methods that help in apartment comparisons.

+++<h4>Larger</h4>+++
Implement the method `public boolean larger(Apartment otherApartment)` that returns
  true if the Apartment object for which the method is called (`this`) is larger than the
  apartment object given as parameter (`otherApartment`).
Example of the usage:
[source,java]
----
Apartment studioManhattan = new Apartment(1, 16, 5500);
Apartment twoRoomsBrooklyn = new Apartment(2, 38, 4200);
Apartment fourAndKitchenBronx = new Apartment(3, 78, 2500);

System.out.println( studioManhattan.larger(twoRoomsBrooklyn) );       // false
System.out.println( fourAndKitchenBronx.larger(twoRoomsBrooklyn) );   // true
----

+++<h4>Price difference</h4>+++

Implement the method `public int priceDifference(Apartment otherApartment)` that
  returns the absolute value of the price difference of the Apartment object for which the method is
  called (`this`) and the apartment object given as parameter
  (`otherApartment`). The price of an apartment is `squareMeters *
    pricePerSquareMeter.`
Example of the usage:
[source,java]
----
Apartment studioManhattan = new Apartment(1, 16, 5500);
Apartment twoRoomsBrooklyn = new Apartment(2, 38, 4200);
Apartment fourAndKitchenBronx = new Apartment(3, 78, 2500);

System.out.println( studioManhattan.priceDifference(twoRoomsBrooklyn) );        // 71600
System.out.println( fourAndKitchenBronx.priceDifference(twoRoomsBrooklyn) );    // 35400
----

+++<h4>more expensive than</h4>+++

Implement the method `public boolean moreExpensiveThan(Apartment otherApartment)`
  that returns true if the Apartment-object for which the method is called (`this`) has a
  higher price than the apartment object given as parameter (`otherApartment`).
Example of the usage:
[source,java]
----
Apartment studioManhattan = new Apartment(1, 16, 5500);
Apartment twoRoomsBrooklyn = new Apartment(2, 38, 4200);
Apartment fourAndKitchenBronx = new Apartment(3, 78, 2500);

System.out.println( studioManhattan.moreExpensiveThan(twoRoomsBrooklyn) );       // false
System.out.println( fourAndKitchenBronx.moreExpensiveThan(twoRoomsBrooklyn) );   // true
----
++++
</details></div><!-- end ex 87 -->
++++
