++++
<div class='ex'><details class='ex'><summary>Exercise 95: Money</summary>
++++



In a previous assignment we stored the balance of a LyyraCard using a double variable. In reality
money should not be represented as a double since the double arithmetics is not accurate. A better
idea would be to implement a class that represents money. We'll start with the following
class skeleton:

[source,java]
----
public class Money {

    private final int euros;
    private final int cents;

    public Money(int euros, int cents) {

        if (cents > 99) {
            euros += cents / 100;
            cents %= 100;
        }

        this.euros = euros;
        this.cents = cents;
    }

    public int euros(){
        return euros;
    }

    public int cents(){
        return cents;
    }

    public String toString() {
        String zero = "";
        if (cents &lt;= 10) {
            zero = "0";
        }

        return euros + "." + zero + cents + "e";
    }
}
----

Notice that the fields `euros` and `cents` have been defined
as `final` meaning that once the variables have been set, the value of those can not be
changed. An object value of which can not be changed is said to be _immutable_. If we need to
e.g. calculate the sum of two money objects, we need to create a new money object that represents
the sum of the originals.

In the following we'll create three methods that are needed in operating with money.

+++<h4>Plus</h4>+++

Let us start by implementing the method `public Money plus(Money added)`, that
returns a _new Money object_ that has a value equal to the sum of the object for which the
method was called and the object given as parameter.

Examples of the method usage:

[source,java]
----
Money a = new Money(10,0);
Money b = new Money(5,0);

Money c = a.plus(b);

System.out.println(a);  // 10.00e
System.out.println(b);  // 5.00e
System.out.println(c);  // 15.00e

a = a.plus(c);          // NOTE: new Money-object is created and reference to that
                        //           is assigned to variable a.
                        //       The Money object 10.00e that variable a used to hold
                        //           is not referenced anymore

System.out.println(a);  // 25.00e
System.out.println(b);  // 5.00e
System.out.println(c);  // 15.00e
----

  +++<h4>less</h4>+++

Create the method `public boolean less(Money compared)`, that returns true if the
object for which the method was called is less valuable than the object given as parameter.

[source,java]
----
Money a = new Money(10,0);
Money b = new Money(3,0);
Money c = new Money(5,0);

System.out.println(a.less(b));  // false
System.out.println(b.less(c));  // true

----

+++<h4>Minus</h4>+++

And finally create the method `public Money minus(Money decremented)`, that returns a
_new Money object_ that has a value equal to the object for which the method was called
minus the object given as parameter. If the value would be negative, the resulting Money object
should have the value 0.

Examples of the method usage:

[source,java]
----
Money a = new Money(10,0);
Money b = new Money(3,50);

Money c = a.minus(b);

System.out.println(a);  // 10.00e
System.out.println(b);  // 3.50e
System.out.println(c);  // 6.50e

c = c.minus(a);         // NOTE: new Money-object is created and reference to that is assigned to variable c
                        //       the Money object 6.50e that variable c used to hold, is not referenced anymore

System.out.println(a);  // 10.00e
System.out.println(b);  // 3.50e
System.out.println(c);  // 0.00e
----

++++
</details></div><!-- end ex 95 -->
++++
