:doctitle: A quick recap.
:tabcolumns: d,h,d,d,d,d,h,d,d,d,d,d,d,d,d,d
include::../commonhead.adoc[]

[#_part1_4]
:numbered!:

== MOOC Material Week 6

:numbered:

== A quick recap

Let us start week 6 with two assignments that use the most important topics of week 5. You might want to
read chapter 23.10 before assignment 94 and chapters 23.6 and 23.12 before assignment 95.

include::{exercises}/ex94.adoc[]

include::{exercises}/ex95.adoc[]
=== Character strings are immutable

The String objects of Java, as with the Money class objects, are unchangeable, _immutable_.
If for example a new object is concatenated to the end of a character string with the + operator, the
original character string doesn't become longer, but a new character string object is born:

[source,java]
----
String characterString = "test";
characterString + "tail";

System.out.println( characterString );  // test
----


We see that the character string cannot be changed, but we can add the value of the new character string
- that was created through concatenation - to the old variable:

[source,java]
----
String characterString = "test";
characterString = characterString + "tail";   // or characterString += "tail";

System.out.println( characterString );  // testtail
----

Despite the ease of use of ArrayList the programs you write sometimes have a need for a `List`, the ancestor of `ArrayList`.footnote[ancestor as in either a super class or an interface]


Now the variable `characterString` refers to a _new_ character string object, which
was created by combining the previous character string value the variable referred to ("test")
with the "tail" character string. Nothing refers to the "test" character string object
anymore.

== Array

During the course, we've used ArrayLists numerous times to store different kinds of objects.
ArrayList is easy to use because it offers a lot of ready-made tools that make the programmer's life a
little easier through automatic growing of a list, thanks to the list which doesn't run out of space
(unless the list grows so large that it makes the program take up all the memory that is reserved for it).

_Array_ is an object that can be understood as a series of _pigeonholes_ for values. The
_length_ or _size_ of an array is the number of spots in that array - the number of items you
can put in the array. The values of an array are called _cells_ of the array. Unlike with
ArrayLists, the size of the array (the amount of cells in an array) cannot be changed, growing an array
always requires creating a new array and copying the cell's content of the old array to the new one.

An array can be created in two ways. Let's take a look at the way in which we give content to the array
at creation. An array of the integer type that consists of 3 cells is defined as follows:

[source,java]
----
int[] numbers = {100, 1, 42};
----


The type of the Array object is denoted as `int[]`, which stands for an array, the cells of which
 are of the type `int`. In the example the name of the array-object is `numbers`
and it holds 3 number values `{100, 1, 42}`. The array is written with curly bracies, in which the values to be inserted into the array are separated by commas.

The values of the array can be of any variable type that we've seen earlier. Below we've first
introduced an array containing character strings and then an array containing floating numbers.

[source,java]
----
String[] characterStringArray = {"Matti P.", "Matti V."};
double[] floatingNumberArray = {1.20, 3.14, 100.0, 0.6666666667};
----


The cells of the array are referred to with _indexes_ that are integers. The index tells the
position of the cell in the array. The first item in an array is in position 0, the next one in position 1, and
so forth. When inspecting a certain value of an array, the index is given after the name of the array
object in brackets.

[source,java]
----
// index           0   1    2    3   4   5     6     7
int[] numbers = {100,  1,  42,  23,  1,  1, 3200, 3201};

System.out.println(numbers[0]);    // prints the number in the array's index 0: the number 100
System.out.println(numbers[2]);    // prints the number in the array's index 2, the number 42
----


The size (length) of the array above is 8.

You'll probably notice that the `get`-method of ArrayList works pretty much the same
as the indexing of an array. Only the notation - the syntax - is different when dealing
with arrays.

Setting an individual value to a certain position in an array happens the same way as with regular
variables, only with arrays the index also has to be mentioned. The index is mentioned inside brackets.

[source,java]
----
int[] numbers = {100,1,42};

numbers[0] = 1;    // setting value 1 to index 0
numbers[1] = 101;  // setting value 101 to index 1

// the numbers array now looks like {1,101,42}
----


If an index points _past an array_, that is, to a cell that doesn't exist, we will get an
error: _ArrayIndexOutOfBoundsException_, which means that the index that we pointed at doesn't
exist. So we cannot refer to a cell that is past the array - to an index that is smaller than 0, or larger
or equals the size of the array.

We'll notice that the array clearly is related to ArrayList. Arrays, as with lists, have
their cells in a certain order!

=== Iteration of an array

The size of an array object can be found out by typing `array.length` into the code, notice
that you don't use parentheses with this one. `array.length()` does not work!

Iterating through the cells of an array is easy to implement with the help of the
`while`-command:

[source,java]
----
int[] numbers = {1, 8, 10, 3, 5};

int i = 0;
while (i &lt; numbers.length ) {
    System.out.println(numbers[i]);
    i++;
}
----


With the help of variable `i` we go through the indexes 0, 1, 2, 3, and 4, and print the
value of the variable in each cell. First `numbers[0]` gets printed, then
`numbers[1]` and so forth. The variable `i` stops getting increased when the array has
been iterated through, that is when `i`'s value is equal to the length of the array.

When iterating through an array it isn't always necessary to list the indexes of it, the only
interesting thing is the values of the array. In this case we can use the for-each-structure - that we
became familiar with earlier - to go through the values. Now only the name of a variable is given in the
frame of the loop, to which each of the values of the array are set one after the other. The name of the
array is separated with a colon.

[source,java]
----
int[] numbers = {1,8,10,3,5};

for (int number : numbers) {
    System.out.println(number);
}
----


[source,java]
----
String[] names = {"Juhana L.", "Matti P.", "Matti L.", "Pekka M."};

for (String name : names) {
    System.out.println(name);
}
----


*Notice:* when using a for-each-type of loop, you cannot set values to the cells of the
array! With the format of the for-sentence we inspect next that can be done too.
=== Another form of the for command

So far when doing loops, we've used while and the for-each form of the for sentence. Another form of
the for-loop exists, which is handy especially when handling arrays. In the following we print the numbers
0, 1 and 2 with a for loop:

[source,java]
----
for (int i = 0; i &lt; 3; i++ ) {
    System.out.println(i);
}
----


The `for` in the example works _exactly_ as the `while` below:

[source,java]
----
int i = 0;  // formatting the variable that will be used in the loop
while ( i &lt; 3 ) {  // condition
System.out.println(i);
i++;   // updating the variable that is used in the loop
}
----


A `for` command, as shown in `for (int i = 0; i &lt; 3; i++ )` above, has three parts to it:
_formatting the loop variables; condition; updating the loop variables_:


* In the first part, the variables that are used in the loop are formatted. In the example above we
 formatted the variable `i` with `int i=0`. The first part is run only once, at
 the beginning of a for run.
* In the second part the condition is defined, which defines how long the code is run in the code
 block that is related to the for loop. In our example the condition was `i &lt; 3`. The
 validity of the condition is checked _before each round of the loop_. The condition works
 exactly the same as the a condition of a while loop works.
* The third part, which in our example is `i++` , is always run once at the end of each
 round of the loop.

Compared to _while_, _for_ is a slightly clearer way of implementing loops of whose
amount of runs is based on, for example, growing a counter. When going through an array the case is usually
exactly this. In the following we print the contents of the `numbers` array with for:

[source,java]
----
int[] numbers = {1, 3, 5, 9, 17, 31, 57, 105};

for(int i = 3; i &lt; 7; i++) {
    System.out.println(numbers[i]);
}
----


[source,java]
----
int[] numbers = {1, 3, 5, 9, 17, 31, 57, 105};

for(int i = 6; i&gt;2 ; i--) {
    System.out.println(numbers[i]);
}
----

=== For and array length

Going through all cells of an array with for happens like this:

[source,java]
----
int[] numbers = {1, 8, 10, 3, 5};

for (int i = 0; i &lt; numbers.length; i++ ) {
    System.out.println(numbers[i]);
}
----


Notice, that in the condition `i < numbers.length` we compare the value of the
loop variable to the length we get from the array. The condition should not in any case be
"hardcoded" as, for example, `i < 5` because often the length of the array
can't be known for sure beforehand.
=== Array as a parameter

Arrays can be used - just as any other objects - as a parameter to a method. Notice that, as with all
objects, the method gets a reference to an array, so all changes done to the content of the array in the
method also show up in the main program.

[source,java]
----
public static void listCells(int[] integerArray) {

    System.out.println("the cells of the array are: ");
    for( int number : integerArray) {
        System.out.print(number + " ");
    }

    System.out.println("");
}

public static void  main(String[] args) {
    int[] numbers = { 1, 2, 3, 4, 5 };
    listCells(numbers);
}
----


As we already know, the name of the parameter within a method can be freely chosen. The name does not
need to be the same as in the one used in calling it. Above, the array is called `integerArray`
within the method and the caller of the method knows the array as `numbers`.

<!-- CAST61-->

include::{exercises}/ex96.adoc[]

include::{exercises}/ex97.adoc[]

=== Creating a new array

If the size of the array isn't always the same, that is, if its size depends on
user input for example, the previously introduced way of creating arrays will not work. It is also possible to create a
table so that its size is defined with the help of a variable:

[source,java]
----
int cells = 99;
int[] array = new int[cells];
----


Above we create an array of the type int, that has 99 cells. This alternative way of creating an
array works just like any other object; with the command `new`. Following the
`new` is the type of the array and in the brackets is the size of the array.

[source,java]
----
int cells = 99;
int[] array = new int[cells]; //creating an array of the size of the value in the 'cells' variable

if(array.length == cells) {
    System.out.println("The length of the array is " + cells);
} else {
    System.out.println("Something unreal happened. The length of the array is something else than " + cells);
}
----


In the following example there is a program that prompts  the user for the amount of values and subsequently
the values. Afterwards, the program prints the values in the same order again. The values given by the user
are stored in the array.

[source,java]
----
System.out.print("How many values? ");
int amountOfValues = Integer.parseInt(reader.nextLine());

int[] values = new int[amountOfValues];

System.out.println("Enter values:");
for(int i = 0; i &lt; amountOfValues; i++) {
    values[i] = Integer.parseInt(reader.nextLine());
}

System.out.println("Values again:");
for(int i = 0; i &lt; amountOfValues; i++) {
    System.out.println(values[i]);
}
----


A run of the program could look something like this:

----
How many values? <span class="red">4</span>
Enter values:
<span class="red">4</span>
<span class="red">8</span>
<span class="red">2</span>
<span class="red">1</span>
Values again:
4
2
8
1
----


=== An array as the return value

Since methods can return objects, they can also return arrays. This particular method that returns an
array looks like this -- notice that arrays might also contain (references to) objects.

[source,java]
----
public static String[] giveStringTable() {
    String[] tchrs = new String[3];

    tchrs[0] = "Bonus";
    tchrs[1] = "Ihq";
    tchrs[2] = "Lennon";

    return tchrs;
}

public static void main(String[] args){
    String[] teachers = giveStringTable();

    for ( String teacher : teachers)
        System.out.println( teacher );
}
----


include::{exercises}/ex98.adoc[]

== About blocks and nested loops
<<blocks>>
A piece of code that begins with a curly bracket `{` and ends with a curly bracket
`}` is called a _block_. As we've already seen, blocks are used - among other things  - to denote the code of conditional sentences and loops.
_An important feature of a block is that variables defined inside of it only exist inside of it!_.

In the following example we define the string variable `stringDefinedWithinBlock` within the
block of a conditional sentence, which therefore will only exist inside of the block. The variable introduced
inside of the block cannot be printed outside of it!

[source,java]
----
int number = 5;

if( number == 5 ){
    String stringDefinedWithinBlock = "Yeah!";
}

System.out.println(stringDefinedWithinBlock); // does not work!
----


However, you can use and manipulate variables defined outside of the block in the block.

[source,java]
----
int number = 5;

if( number == 5 ) {
    number = 6;
}

System.out.println(number); // prints 6
----


You can have any kind of code within a block. For example, a for loop can have another for loop inside of it
or say, a while loop. Let's inspect the following program:

[source,java]
----
for(int i = 0; i &lt; 3; i++) {
   System.out.print(i + ": ");

   for(int j = 0; j &lt; 3; j++) {
      System.out.print(j + " ");
   }

   System.out.println();
}
----


The program prints the following:

----
0: 0 1 2
1: 0 1 2
2: 0 1 2
----


So what happens in the program? If we only think about the outer for loop, its functionality is
easy to understand:

[source,java]
----
for(int i = 0; i &lt; 3; i++) {
   System.out.print(i + ": ");

   // the inner for-loop

   System.out.println();
}
----


So first `i=0` prints `0:` and a line break thanks to `System.out.println();`. After this, `i` grows and 1 is
printed and so forth, so the outer for makes this happen:

----
0:
1:
2:
----


The inner for loop is also easy to understand separately. It prints out `0 1 2`. When we
combine these two, we'll notice that the inner for loop carries out its print just before the
outer for loop's line break.
=== Variables defined outside of a for loop as its condition

Let's inspect the following alteration to the previous example:

[source,java]
----
for(int i = 0; i &lt; 3; i++) {
    System.out.print(i + ": ");

    for(int j = 0; j &lt;= i; j++) {
        System.out.print(j + " ");
    }

    System.out.println();
}
----


The amount of runs the inner for loop now depends on the value of the variable `i` of
the outer loop. So when `i=0` the inner loop prints 0, when `i=1` the inner loop
prints 0 1. The entire output of the program is as follows:

----
0: 0
1: 0 1
2: 0 1 2
----


            The following program prints out the multiplication tables of the numbers 1 .. 10.

[source,java]
----
for(int i = 1; i &lt;= 10; i++) {

    for(int j = 1; j &lt;= 10; j++) {
        System.out.print(i * j + " ");
    }

    System.out.println();
}
----


The output looks like this:

----
1 2 3 4 5 6 7 8 9 10
2 4 6 8 10 12 14 16 18 20
3 6 9 12 15 18 21 24 27 30
4 8 12 16 20 24 28 32 36 40
5 10 15 20 25 30 35 40 45 50
6 12 18 24 30 36 42 48 54 60
7 14 21 28 35 42 49 56 63 70
8 16 24 32 40 48 56 64 72 80
9 18 27 36 45 54 63 72 81 90
10 20 30 40 50 60 70 80 90 100
----


The topmost row has the multiplication table of 1. At the beginning `i=1` and the inner
loop's variable `j` gets the values 1...10. For each `i, j` value pair their
product is printed. So at the beginning `i=1, j=1`, then `i=1, j=2`, ..., `i=1, j=10` next `i=2, j=1`, and so forth.

Of course the multiplication table program can be cut in to smaller pieces, too. We can define the
methods `public void printMultiplicationTableRow(int multiplier, int howManyTimes)` and
`public void printMultiplicationTable(int upTo)`, in this case the structure of our program
could be as follows:

[source,java]
----
public class MultiplicationTable {

    public void print(int upTo) {
        for(int i = 1; i &lt;= upTo; i++) {
            printMultiplicationTableRow(i, upTo);

            System.out.println();
        }
    }

    public void printMultiplicationTableRow(int multiplier, int howManyTimes) {
        for(int i = 1; j &lt;= howManyTimes; i++) {
            System.out.print(i * multiplier + " ");
        }
    }
}
----


Now calling `new MultiplicationTable().print(5);` prints the tables below.

----
1 2 3 4 5
2 4 6 8 10
3 6 9 12 15
4 8 12 16 20
5 10 15 20 25
----


include::{exercises}/ex99.adoc[]

include::{exercises}/ex100.adoc[]

== To static or not to static?

When we started using objects, the material advised to leave out the keyword 'static' when
defining their methods. However, up until week 3 all of the methods included that keyword. So what is it
all about?

The following example has a method `resetArray`, that works as its name implies; it sets
all of the cells of an array that it receives as a parameter to 0.

[source,java]
----
public class Program {

    public static void resetArray(int[] table) {
        for ( int i=0; i &lt; table.length; i++ )
            table[i] = 0;
    }

    public static void main(String[] args) {
        int[] values = { 1, 2, 3, 4, 5 };

        for ( int number : values ) {
            System.out.print( number + " " );  // prints 1, 2, 3, 4, 5
        }

        System.out.println();

        resetArray(values);

        for ( int number : values ) {
            System.out.print( number + " " );  // prints 0, 0, 0, 0, 0
        }
    }
}
----


We notice that the method definition now has the keyword `static`. The reason for that is
that the method does not operate on any object, instead it is a _class method_ or in other words
_static methods_. In contrast to instance methods, static methods are not connected to any
particular object and thus the reference `this` is not valid within static methods. A static
method can operate only with data that is given it as parameter. The parameter of a static method can
naturally be an object.

Since static methods are not connected to any object, they can not be called through the object name:
`objectName.methodName()` but should be called as in the above example by using only the method
name.

If the static method is called from a different class, the call is of the form
`ClassName.staticMethodName()`. The below example demonstrates that:

[source,java]
----
public class Program {
    public static void main(String[] args) {
        int[] values = { 1, 2, 3, 4, 5 };

        for ( int value : values ) {
            System.out.print( value + " " );  // prints: 1, 2, 3, 4, 5
        }

        System.out.println();

        ArrayHandling.resetArray(values);

        for ( int value : values ) {
            System.out.print( value + " " );  // prints: 0, 0, 0, 0, 0
        }
    }
}
----


[source,java]
----
public class ArrayHandling {
    public static void resetArray(int[] array) {
        for ( int i=0; i &lt; array.length; i++ ) {
            array[i] = 0;
        }
    }
}
----


The static method that has been defined within another class will now be called with
`ArrayHandling.resetArray(_parameter_);`.
=== When static methods should be used

All object state-handling methods should be defined as normal object methods. For example, all of the
methods of the `Person, MyDate, Clock, Team, ...` classes we defined during the previous weeks
should be defined as normal object methods, not as statics.

Lets get back to the `Person` class yet again. The following is a part of the class
definition. All of the object variables are referred to with the `this` keyword because we
emphasize that we are handling the object variables 'within' the said object:

[source,java]
----
public class Person {
    private String name;
    private int age;

    public Person(String name) {
        this.age = 0;
        this.name = name;
    }

    public boolean isAdult(){
        if ( this.age &lt; 18 ) {
            return false;
        }

        return true;
    }

    public void becomeOlder() {
        this.age++;
    }

    public String getName() {
        return this.name;
    }
}
----

Because the methods manipulate the object, they do not need to be defined as static, or in other words
don't belong to the object. If we try to do this, the program won't work:

[source,java]
----
public class Person {
    //...

    public static void becomeOlder() {
        this.age++;
    }
}
----


As a result we'll get an error _non-static variable age can not be referenced from static context_,
which means that a static method cannot handle an object method.

So when should a static method be used then? Let us inspect the Person object handling, an example familiar
from chapter 23:

[source,java]
----
public class Program {
    public static void main(String[] args) {
        Person pekka = new Person("Pekka");
        Person antti = new Person("Antti");
        Person juhana = new Person("Juhana");

        for ( int i=0; i &lt; 30; i++ ) {
            pekka.becomeOlder();
            juhana.becomeOlder();
        }

        antti.becomeOlder();

        if ( antti.isAdult() ) {
            System.out.println( antti.getName() + " is an adult" );
        } else {
            System.out.println( antti.getName() + " is a minor" );
        }

        if ( pekka.isAdult() ) {
            System.out.println( pekka.getName() + " is an adult" );
        } else {
            System.out.println( pekka.getName() + " is a minor" );
        }

        if ( juhana.isAdult() ) {
            System.out.println( juhana.getName() + " is an adult" );
        } else {
            System.out.println( juhana.getName() + " is a minor" );
        }
    }
}
----


We'll notice that the piece of code that reports the maturity of persons is copy-pasted twice in
the program. It looks really bad!

Reporting the maturity of a person is an excellent candidate for a static method. Let's rewrite the
program using that method:

[source,java]
----
public class Main {

    public static void main(String[] args) {
        Person pekka = new Person("Pekka");
        Person antti = new Person("Antti");
        Person juhana = new Person("Juhana");

        for ( int i=0; i &lt; 30; i++ ) {
            pekka.becomeOlder();
            juhana.becomeOlder();
        }

        antti.becomeOlder();

        reportMaturity(antti);

        reportMaturity(pekka);

        reportMaturity(juhana);
    }

    private static void reportMaturity(Person person) {
        if ( person.isAdult() ) {
            System.out.println(person.getName() + " is an adult");
        } else {
            System.out.println(person.getName() + " is a minor");
        }
    }
}
----


The method `reportMaturity` is defined as static so it doesn't belong to any object,
*but* the method receives a Person object as a parameter. The method is not defined within
the Person-class since even though it handles a Person object which it receives as a parameter, it is an
helper method of the main program we just wrote. With the method we've made main more readable.

include::{exercises}/ex101.adoc[]

== Assignments where you are free to decide how to structure the program.

include::{exercises}/ex102.adoc[]

include::{exercises}/ex103.adoc[]


== Sorting an array

We're back to arrays again!

=== Sorting an array with the ready-made tools of Java.

As we've seen, there are all kinds of useful things already in Java. For example for handling
ArrayLists you can find many useful helper methods in the class Collections. For arrays you can find helpful
methods in the class `Arrays`. Sorting a table can be done with
`Arrays.sort(array)`.

Note: To be able to use the command you must have the following definition at the top of the program
file:

[source,java]
----
import java.util.Arrays;
----


If you forget to write the `import` line, NetBeans will offer help with writing it. Try
clicking the picture of the light bulb that appears to the left of the line of code that is underlined with
red.

The following program creates arrays and sorts the values in the array with the `Arrays.sort`-command.

[source,java]
----
int[] values = {-3, -111, 7, 42};
Arrays.sort(values);
for(int value: values) {
    System.out.println(value);
}
----


----
-111
-3
7
42
----

=== Implementation of a sorting algorithm

It's easy to sort an array with the ready-made tools of Java. The general knowledge of a program
requires knowing at least one sorting algorithm (or in other words, a way to sort an array). Let's get
familiar with the "classic" sorting algorithm, choice sorting. Let's do this with a few
excercises.

include::{exercises}/ex104.adoc[]

== Searching

In addition to sorting, another very typical problem that a programmer runs into is finding a certain
value in an array. Earlier, we've implemented methods that search for values in lists and arrays. In
the case of arrays, values and strings can be searched for in the following way:

[source,java]
----
public static boolean isInArray(int[] array, int searchingFor) {
    for ( int value : array ) {
       if ( value == searchingFor )  {
           return true;
       }
    }

    return false;
}

public static boolean isWordInArray(String[] array, String searchingFor) {
    for ( String word: array ) {
        if ( word.equals(searchingFor) )  {
            return true;
        }
    }

    return false;
}
----


An implementation like this is the best we've been able to do so far. The downside of the method is
that, if the array has a very large amount of values in it, the search will take a lot of time. In the worst
case scenario the method goes through every single cell in the array. This means that going through an
array that has 16777216 cells does 16777216 cell inspections.

On the other hand, if the values in an array are <i>ordered by size</i>, the search can be done in a
notably faster way by applying a technique called <i>binary search</i>. Let's investigate the idea of binary
search with this array:

++++
<pre>
// indexes   0   1   2   3    4   5    6   7   8   9  10
// values     -7  -3   3   7   11  15   17  21  24  28  30
</pre>
++++


Let's assume that we want to find the value 17. Let's utilize the information that the values of the array
are in order instead of going through the array from the beginning. Let's inspect the middle cell of the
array. The middle cell is 5 (the largest index 10 divided by two). The middle cell is marked with the
asterisk:

++++
<pre>
                                   *
// indexes   0   1   2   3    4   5    6   7   8   9  10
// values     -7  -3   3   7   11  15   17  21  24  28  30
</pre>
++++


At the middle is the value 15, which was not the value we were looking for. We're looking for the
value 17, so since the cells of the array are ordered by size, the value cannot be on the left side of the             15.
So we can determine that all indexes that are smaller or equal to 5 do not have the value we are
looking for.

The area where we are searching for the value we want to find can now be limited to values that are on
the right side of the index 5, or in other words, in the indexes [6, 10] (6, 7, 8, 9, 10). In the following,
the searched value cannot be in the part of the array which is grey:

++++
<pre>
// indexes   <font color="lightgrey"> 0   1   2   3   4    5</font>    6     7   8   9  10
// values      <font color="lightgrey">-7  -3   3   7  11   15</font>   17   21  24  28  30
</pre>
++++


Next, let's inspect the middle index of the area that we have left; the middle index of indexes 6-10. The
middle index can be found by getting the sum of the smallest and largest index and dividing it by two:
(6+10)/2 = 16/2 = 8. The index 8 is marked with the asterisk below.

++++
<pre>
                                                 *
// indexes   <font color="lightgrey"> 0   1   2   3   4    5</font>    6   7   8   9  10
// values      <font color="lightgrey">-7  -3   3   7  11   15</font>   17   21  24  28  30
</pre>
++++


In index 8, we have the value 24, which was not the value we were looking for. Because the values in the
array are ordered by size, the value we are searching for can not, in any case, be on the right side of the
value 24. We can deduce that all indexes that are larger or equal to 8 can not contain the value we are
looking for. The search area gets narrowed down again, the grey areas have been dealt with:

++++
<pre>
// indexes   <font color="lightgrey"> 0   1   2   3   4    5</font>    6   7  <font color="lightgrey"> 8   9  10</font>
// values      <font color="lightgrey">-7  -3   3   7  11   15</font>   17   21  <font color="lightgrey">24  28  30</font>
</pre>
++++


The search continues. Let's inspect the middle index of the area that we have left to search, that is, the
middle index of indexes 6-7. The middle index can again be found out by getting the sum of the smallest and
largest index of the search area and then dividing it by two: (6+7)/2 = 6.5, which is rounded down to 6.
The spot has been marked with the asterisk.

++++
<pre>
                                         *
// indexes   <font color="lightgrey"> 0   1   2   3   4    5</font>    6    7  <font color= "lightgrey"> 8   9  10</font>
// values      <font color="lightgrey">-7  -3   3   7  11   15</font>   17   21  <font color="lightgrey">24  28  30</font>
</pre>
++++

In the index 6 we have the value 17, which is the same as the value we've been looking for. We can
stop the search and report that the value we searched for is in the array. If the value wouldn't have
been in the array - for example if the searched-for value would've been 16 - the search area would have
eventually been reduced to nothing.

++++
<pre>
                                         *
// indexes   <font color="lightgrey"> 0   1   2   3   4    5</font>    <font color="red">6</font>   7  <font color=
"lightgrey"> 8   9  10</font>
// values      <font color="lightgrey">-7  -3   3   7  11   15</font>    <font color="red">17</font>  21  <font color=
"lightgrey">24  28  30</font>
</pre>
++++


So for the idea of binary search to become clear to you, simulate with pen and paper how the binary
search works when the array is the one below and first you're searching for value 33 and then value
1.

++++
<pre>
// indexes   0   1   2   3   4   5   6   7   8   9  10  11  12  13
// values     -5  -2   3   5   8  11  14  20  22  26  29  33  38  41
</pre>
++++


With the help of binary search we look for cells by always halving the inspected area. This enables us
to search in a very efficient way. For example, an array of size 16 can be divided in half up to 4
times, so 16 -> 8 > 4 -> 2 -> 1. On the other hand, an array that has 16777216 cells can be
halved up to 24 times. This means that with binary search we only need to inspect up to 24 cells in an
array that has 16777216 cells in order to find our desired cell.

_The efficiency of binary search can be inspected with logarithms. A base two logarithm
(log^2 ) of the number 16777216 is 24 -- with the base two logarithm we can calculate
how many times a number can be halved. Respectively the base two logarithm of the number 4294967296
(log^2) is 32. This means that searching from a sorted array of
4294967296 different values would only take up to 32 cell inspections. Efficiency is an essential part of
computer science._

include::{exercises}/ex105.adoc[]

include::{exercises}/ex106.adoc[]



== About arrays and objects

If need be, any type of object can be put into an array. In the following, an example of an array into
which will be put _Person_ objects:

[source,java]
----
public static void main(String[] args) {
    Person[] persons = new Person[3];

    persons[0] = new Person("Pekka");
    persons[1] = new Person("Antti");
    persons[2] = new Person("Juhana");

    for ( int i=0; i &lt; 30; i++ ) {
        persons[0].becomeOlder();
        persons[1].becomeOlder();
        persons[2].becomeOlder();
    }

    for ( Person person : persons ) {
        reportMaturity(person);
    }
}
----


First we create an array that can hold 3 Person objects. We put Pekka in slot 0, Antti in 1 and Juhana
in 2. We age all by 30 years and check all of their maturity with the help of the method from the
previous chapter.

The same example with ArrayLists:

[source,java]
----
public static void main(String[] args) {
    ArrayList&lt;Person&gt; persons = new ArrayList&lt;Person&gt;();

    persons.add( new Person("Pekka") );
    persons.add( new Person("Antti") );
    persons.add( new Person("Juhana") );

    for ( int i=0; i &lt; 30; i++ ) {
        for ( Person person : persons ) {
            person.becomeOlder();
        }

        //  or persons.get(0).becomeOlder();
        //     persons.get(1).becomeOlder();
        //     ...
    }

    for ( Person person : persons ) {
        reportMaturity(person);
    }
}
----


In most situations it's better to use ArrayList instead of an array. However there can be cases where
an array is adequate and is simpler to use.

A week always consists of seven days. It would be meaningful to form it out of exactly 7 Day objects. Since
there's always 7 Day objects, an array will suit the situation very well:

[source,java]
----
public class Day {
    private String name;
    // ...
}

public class Week {
    private Day[] days;

    public Week(){
        days = new Day[7];
        days[0] = new Day("Monday");
        days[1] = new Day("Tuesday");
        // ...
    }
}
----
