++++
<div class='ex'><details class='ex'><summary>Exercise 75: Decreasing counter</summary>
++++

The starting point of this exercise is a partially implemented class
`DecreasingCounter`:


[source,java]
----
public class DecreasingCounter {
  private int value;   // object variable that remembers the value of the counter

  public DecreasingCounter(int valueAtStart) {
      this.value = valueAtStart;
  }

  public void printValue() {
      System.out.println("value: " + this.value);
  }

  public void decrease() {
      // write here the code that decrements the value of counter by one
  }

  // and here the rest of the methods
}
----

The counter can be used as follows:

[source,java]
----
public class Main {
  public static void main(String[] args) {
      DecreasingCounter counter = new DecreasingCounter(10);

      counter.printValue();

      counter.decrease();
      counter.printValue();

      counter.decrease();
      counter.printValue();
  }
}
----

Output should be:

[source]
----
value: 10
value: 9
value: 8
----

The constructor of `DecreasingCounter` receives as parameter the initial value of
the counter. In the example, the constructor parameter is `10`, which is then set to the
object variable `this.value`. The value of the counter can be printed with the method
`printValue()`. The method `decrease()` should decrease the value of the
counter by one.

++++
<h4>Implementing method decrease()</h4>
++++

Implement the method `decrease()` so that when called, the object variable
`this.value` is decreased by one. When this is done, your program should work as the
example above.

  <h4>Value remains positive</h4>

  Change your implementation of the method `decrease()` so that the value of the
  counter will not drop below zero. If the method is called when the value is zero, nothing
  should happen:

[source,java]
----
public class Main {
  public static void main(String[] args) {
      DecreasingCounter counter = new DecreasingCounter(2);

      counter.printValue();

      counter.decrease();
      counter.printValue();

      counter.decrease();
      counter.printValue();

      counter.decrease();
      counter.printValue();
  }
}
----

Output should be:

[source]
----
value: 2
value: 1
value: 0
value: 0
----

++++
<h4>Counter reset</h4>
++++

Implement the method `public void reset()` that sets the value of the counter to
zero. Example of usage:

[source,java]
----
public class Main {
  public static void main(String[] args) {
      DecreasingCounter counter = new DecreasingCounter(100);

      counter.printValue();

      counter.reset();
      counter.printValue();

      counter.decrease();
      counter.printValue();
  }
}
----

  Output:

[source]
----
value: 100
value: 0
value: 0
----

++++
<h4>Back to initial value</h4>
++++
Implement the method `public void setInitial()`, which returns the counter to its
initial value:

[source,java]
----
public class Main {
  public static void main(String[] args) {
      DecreasingCounter counter = new DecreasingCounter(100);

      counter.printValue();

      counter.decrease();
      counter.printValue();

      counter.decrease();
      counter.printValue();

      counter.reset();
      counter.printValue();

      counter.setInitial();
      counter.printValue();
  }
}
----

Output:

[source]
----
value: 100
value: 99
value: 98
value: 0
value: 100
----

*Hint*: add to the class a new object variable that remembers the initial
value of the counter
++++
</details></div><!-- end ex 75-->
++++
